version: '2'
services:
  web:
    build: .
    command: npm run dev
    expose:
      - '8080'
    ports:
      - '8080:8080'
    volumes:
      - .:/app:rw
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=warn